{
 "title": "GrafanaHomework",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP average duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_milliseconds_sum[5m]) / rate(http_requests_milliseconds_count[5m])\n",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Calculator Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(calculator_errors_total[5m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "HTTP requests per route",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "{{route}}" }
   ]
  },
  {
   "title": "Last Values",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_sum1n", "legendFormat": "sum1n" },
    { "expr": "last_fibo", "legendFormat": "fibo" },
    { "expr": "last_calculator", "legendFormat": "calculator" },
    { "expr": "list_size", "legendFormat": "list size" }
   ]
  }
 ]
}